from __future__ import annotations

import json
import time
from typing import Any

from openai import OpenAI

from app.config import settings
from app.prompts.report_prompts import (
    INCIDENT_REPORT_SYSTEM,
    INCIDENT_REPORT_USER_TEMPLATE,
)


def _client() -> OpenAI:
    return OpenAI(api_key=settings.openai_api_key)


def generate_incident_report(
    incident_id: str,
    title: str,
    severity: str,
    started_at: str | None,
    resolved_at: str | None,
    affected_services: list[str] | None,
    context_logs: list[str] | None,
) -> dict[str, Any]:
    """Call the LLM and return a structured report dict.

    Falls back to a deterministic stub when no API key is configured so that
    the service starts and is testable in development without credentials.
    """
    if not settings.openai_api_key:
        return _stub_report(incident_id, title, severity, started_at, resolved_at, affected_services)

    user_msg = INCIDENT_REPORT_USER_TEMPLATE.format(
        incident_id=incident_id,
        title=title,
        severity=severity or "unknown",
        started_at=started_at or "[unknown]",
        resolved_at=resolved_at or "[unknown]",
        affected_services=", ".join(affected_services or []) or "[unknown]",
        context_logs="\n".join(context_logs or []) if context_logs else "[no logs provided]",
    )

    client = _client()
    start = time.perf_counter()
    completion = client.chat.completions.create(
        model=settings.openai_model,
        messages=[
            {"role": "system", "content": INCIDENT_REPORT_SYSTEM},
            {"role": "user", "content": user_msg},
        ],
        max_tokens=settings.openai_max_tokens,
        response_format={"type": "json_object"},
        temperature=0.2,
    )
    duration_ms = (time.perf_counter() - start) * 1000

    raw = completion.choices[0].message.content or "{}"
    result: dict[str, Any] = json.loads(raw)
    result["model"] = settings.openai_model
    result["prompt_version"] = settings.report_prompt_version
    result["duration_ms"] = round(duration_ms, 1)
    return result


def _stub_report(
    incident_id: str,
    title: str,
    severity: str,
    started_at: str | None,
    resolved_at: str | None,
    affected_services: list[str] | None,
) -> dict[str, Any]:
    """Development stub — returns a well-structured placeholder report instantly."""
    svcs = affected_services or ["[unknown]"]
    return {
        "summary": (
            f"[STUB] Incident {incident_id} ({severity}) — {title}. "
            f"Affected services: {', '.join(svcs)}. "
            "This report was generated by the development stub; replace with a real OpenAI key."
        ),
        "timeline": (
            "| Time (UTC) | Event |\n"
            "| --- | --- |\n"
            f"| {started_at or '[unknown]'} | Incident detected |\n"
            f"| {resolved_at or '[unknown]'} | Incident resolved |"
        ),
        "affected_services": svcs,
        "impact_analysis": "[STUB] Impact analysis not available without LLM credentials.",
        "root_cause": "[STUB] Root cause not determined — LLM credentials missing.",
        "resolution": "[STUB] Resolution steps not generated.",
        "preventive_actions": "1. Configure OPENAI_API_KEY in .env [Owner: Platform team]",
        "model": "stub",
        "prompt_version": settings.report_prompt_version,
        "duration_ms": 0.0,
    }
