from __future__ import annotations

"""Export handlers — convert structured report dicts into PDF bytes or Markdown strings."""

import io
import logging
from datetime import datetime
from pathlib import Path
from typing import Any

import markdown as md_lib

logger = logging.getLogger("audit.exporters")

_TEMPLATE_DIR = Path(__file__).parent.parent / "templates"


def _md_section(heading: str, body: str | None) -> str:
    return f"## {heading}\n\n{body or '_Not available._'}\n\n"


def report_to_markdown(report: dict[str, Any]) -> str:
    """Render a report dict as a Markdown string."""
    lines = [
        f"# {report.get('title', 'Incident Report')}\n",
        f"**Incident ID:** {report.get('incident_id', '—')}  ",
        f"**Severity:** {(report.get('severity') or '—').upper()}  ",
        f"**Status:** {report.get('status', '—')}  ",
        f"**Started:** {report.get('started_at') or '—'}  ",
        f"**Resolved:** {report.get('resolved_at') or '—'}  ",
        f"**Affected services:** {', '.join(report.get('affected_services') or []) or '—'}  ",
        f"**Generated:** {report.get('created_at') or datetime.utcnow().isoformat()}  ",
        "",
    ]
    lines.append(_md_section("Summary", report.get("summary")))
    lines.append(_md_section("Timeline", report.get("timeline")))
    lines.append(_md_section("Impact Analysis", report.get("impact_analysis")))
    lines.append(_md_section("Root Cause", report.get("root_cause")))
    lines.append(_md_section("Resolution", report.get("resolution")))
    lines.append(_md_section("Preventive Actions", report.get("preventive_actions")))
    lines.append("\n---\n_Report generated by LogPilot_\n")
    return "\n".join(lines)


def report_to_pdf_bytes(report: dict[str, Any]) -> bytes:
    """Render a report dict as PDF bytes via WeasyPrint + Jinja2 HTML template."""
    try:
        from jinja2 import Environment, FileSystemLoader
        from weasyprint import HTML  # type: ignore

        env = Environment(loader=FileSystemLoader(str(_TEMPLATE_DIR)), autoescape=True)
        template = env.get_template("report.html.j2")

        # Convert markdown sections to HTML snippets
        timeline_html = md_lib.markdown(report.get("timeline") or "", extensions=["tables"])
        preventive_html = md_lib.markdown(report.get("preventive_actions") or "")

        html_content = template.render(
            **report,
            timeline_html=timeline_html,
            preventive_actions_html=preventive_html,
        )

        pdf_bytes: bytes = HTML(string=html_content).write_pdf()
        return pdf_bytes

    except ImportError as exc:
        logger.warning("WeasyPrint not available, falling back to HTML bytes: %s", exc)
        # Return HTML as fallback — still useful for download
        return _html_fallback(report).encode("utf-8")


def _html_fallback(report: dict[str, Any]) -> str:
    """Minimal HTML fallback when WeasyPrint is not available."""
    body = md_lib.markdown(report_to_markdown(report), extensions=["tables"])
    return f"<!DOCTYPE html><html><body>{body}</body></html>"
